### ISSUE TITLE
MyPage 기능구현

### ISSUE THREAD

**Issue by Celox16** [Green-Challenge/Green-Challenge#24]
## Problem & Opportunity
계산 알고리즘 생성

## Context or Reproduce
마이 페이지 - 차트 통계

## Checklist
 - [ ] 전체 챌린지 가져오기
 - [ ] 탄소저감량 계산하기
 - [ ] 저감량 차트 형식변환하기

**Comment by cfhj8520** [comment]
변경사항 발생에 따른 이슈 닫기
