### ISSUE TITLE
메인화면 기능 구현

### ISSUE THREAD

**Issue by isyoo1213** [Green-Challenge/Green-Challenge#25]
## Problem & Opportunity
메인화면 관련 api 구현

## Context or Reproduce
메인화면 내 참여 중인 챌린지 정보, 참여가능 챌린지 조회 기능 구현

## Checklist
 - [ ] 사용일 / 나무심기 조회
 - [ ] 참여 중인 챌린지 조회
 - [ ] 참여 가능 챌린지 조회

**Comment by cfhj8520** [comment]
변경사항 발생에 따른 이슈 닫기
